services:
  airflow:
    build:
      context: ./airflow
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DATA_DIR: /opt/airflow/data
      EXTRACT_DIR: /opt/airflow/extract
      TRANSFORM_DIR: /opt/airflow/transform
      DBT_DUCKDB_PATH: /opt/airflow/transform/warehouse.duckdb
      PYTHONPATH: /opt/airflow/extract
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./extract:/opt/airflow/extract
      - ./data:/opt/airflow/data
      - ./transform:/opt/airflow/transform
    restart: unless-stopped

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      PARQUET_PATH: /data/sec_ai_10k.parquet
    volumes:
      - ./data:/data:ro
    restart: unless-stopped
